name: flutter_easy_dropdown
description: "Simple and robust Searchable Dropdown with item search feature, making it possible to use an offline item list or filtering URL for easy customization."
version: 1.0.1
homepage: "https://github.com/rohitsoni9/easy_dropdown"

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  pagination_view: ^2.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
    
flutter: null